version: "3.9"
services:
  webapp:
    build:
      context: ./
      args:
        redis_host: redis
    depends_on:
      - redis
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "80:80/tcp"
    networks:
      - application
  redis:
    image: redis
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379/tcp"
    networks:
      - application
networks:
  application: